categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Previous
next: Next
comment: Comment
archive_a: Archive
archive_b: Archive: %s
page: Page %d
recent_posts: Recent Posts